# Generated By AI - Claude Haiku for Auxiliated Study

"""
╔════════════════════════════════════════════════════════════════════════════╗
║                  🎓 OBJECT-ORIENTED PROGRAMMING (OOP) 🎓                  ║
║                        COMPLETE LESSON ON CLASSES                         ║
╚════════════════════════════════════════════════════════════════════════════╝
"""

# ═════════════════════════════════════════════════════════════════════════════
# 📌 PART 1: WHAT ARE CLASSES? 📌
# ═════════════════════════════════════════════════════════════════════════════

"""
A CLASS is a blueprint or "template" for creating objects (instances).

Analogy: 
  🏠 A class is like the blueprint of a house.
  🏠 An object is a real house built following that blueprint.

Why use classes?
  ✅ Organize code
  ✅ Reuse code
  ✅ Simulate real-world objects
  ✅ Facilitate maintenance
"""

# ═════════════════════════════════════════════════════════════════════════════
# 📌 PART 2: BASIC SYNTAX 📌
# ═════════════════════════════════════════════════════════════════════════════

"""
The basic syntax of a class in Python:

    class ClassName:
        def __init__(self, parameters):
            # Initialize attributes
            self.attribute = value
        
        def method(self):
            # Method code
            pass
"""

# ═════════════════════════════════════════════════════════════════════════════
# 📌 EXAMPLE 1: SIMPLE CLASS - PERSON 📌
# ═════════════════════════════════════════════════════════════════════════════

class Person:
    """
    A simple class that represents a Person.
    Demonstrates basic concepts: attributes and methods.
    """
    
    # Constructor (special method __init__)
    # This method is called automatically when you create an object
    def __init__(self, name: str, age: int):
        """
        Define the initial attributes of the object.
        
        Args:
            name (str): Name of the person
            age (int): Age of the person
        """
        self.name = name  # Attribute: stores the name
        self.age = age  # Attribute: stores the age
    
    def introduce(self) -> None:
        """Method that displays an introduction of the person."""
        print(f"👋 Hello! My name is {self.name} and I'm {self.age} years old.")
    
    def have_birthday(self) -> None:
        """Method that increments the age by 1 year."""
        self.age += 1
        print(f"🎂 Happy birthday! {self.name} is now {self.age} years old!")
    
    def get_information(self) -> str:
        """Returns the person's information as a string."""
        return f"Name: {self.name} | Age: {self.age} years"


# 🔹 USING THE PERSON CLASS
print("\n" + "="*70)
print("🔹 EXAMPLE 1: Using the Person Class")
print("="*70)

person1 = Person("John", 25)  # Creating an instance (object)
person1.introduce()  # Calling a method
print(f"📋 {person1.get_information()}")

person1.have_birthday()  # Calling another method


# ═════════════════════════════════════════════════════════════════════════════
# 📌 EXAMPLE 2: CLASS WITH PRIVATE ATTRIBUTES 📌
# ═════════════════════════════════════════════════════════════════════════════

class BankAccount:
    """
    A class that represents a Bank Account.
    Demonstrates the concept of ENCAPSULATION (private attributes).
    """
    
    def __init__(self, holder: str, initial_balance: float = 0.0):
        """
        Initializes a bank account.
        
        Args:
            holder (str): Name of the account holder
            initial_balance (float): Initial account balance (default: 0.0)
        """
        self.holder = holder
        self.__balance = initial_balance  # __ indicates it's private (don't access directly)
        self.__history = []  # Records all transactions
    
    def deposit(self, amount: float) -> None:
        """Makes a deposit to the account."""
        if amount <= 0:
            print("❌ Error: Amount must be positive!")
            return
        
        self.__balance += amount
        self.__history.append(f"✅ Deposit: +${amount:.2f}")
        print(f"💰 Deposit of ${amount:.2f} made successfully!")
    
    def withdraw(self, amount: float) -> None:
        """Makes a withdrawal from the account."""
        if amount <= 0:
            print("❌ Error: Amount must be positive!")
            return
        
        if amount > self.__balance:
            print(f"❌ Error: Insufficient balance! Your balance is ${self.__balance:.2f}")
            return
        
        self.__balance -= amount
        self.__history.append(f"❌ Withdrawal: -${amount:.2f}")
        print(f"💵 Withdrawal of ${amount:.2f} made successfully!")
    
    def check_balance(self) -> float:
        """Returns the current account balance."""
        return self.__balance
    
    def display_balance(self) -> None:
        """Displays the balance in a formatted way."""
        print(f"💳 [{self.holder}] Balance: ${self.__balance:.2f}")
    
    def view_history(self) -> None:
        """Displays the transaction history."""
        print(f"\n📜 HISTORY FOR {self.holder}:")
        if not self.__history:
            print("   No transactions yet.")
        else:
            for transaction in self.__history:
                print(f"   {transaction}")


# 🔹 USING THE BANK ACCOUNT CLASS
print("\n" + "="*70)
print("🔹 EXAMPLE 2: Using the BankAccount Class")
print("="*70)

account = BankAccount("Maria Silva", 1000.0)
account.display_balance()

account.deposit(500)
account.withdraw(200)
account.display_balance()

account.view_history()


# ═════════════════════════════════════════════════════════════════════════════
# 📌 EXAMPLE 3: INHERITANCE (Subclasses) 📌
# ═════════════════════════════════════════════════════════════════════════════

"""
INHERITANCE allows a class to INHERIT attributes and methods from another class.

Example:
    class Animal:        <- PARENT class (superclass)
        pass
    
    class Dog(Animal):  <- CHILD class (subclass)
        pass
"""

class Animal:
    """PARENT class - Represents a generic animal."""
    
    def __init__(self, name: str, age: int):
        self.name = name
        self.age = age
    
    def make_sound(self) -> None:
        """Method that the subclass can override."""
        print(f"🔊 {self.name} makes a sound!")


class Dog(Animal):
    """CHILD class - Inherits from Animal and adds its own characteristics."""
    
    def __init__(self, name: str, age: int, breed: str):
        super().__init__(name, age)  # Calls the PARENT class constructor
        self.breed = breed
    
    def make_sound(self) -> None:
        """Override the PARENT class method."""
        print(f"🐕 {self.name} barks: Woof woof woof!")
    
    def fetch_ball(self) -> None:
        """Method exclusive to the Dog class."""
        print(f"🎾 {self.name} ran after the ball!")


class Cat(Animal):
    """Another CHILD class - Inherits from Animal."""
    
    def make_sound(self) -> None:
        """Override the PARENT class method."""
        print(f"🐱 {self.name} meows: Meow meow!")
    
    def scratch_sofa(self) -> None:
        """Method exclusive to the Cat class."""
        print(f"😼 {self.name} scratched the sofa! (Oops!)")


# 🔹 USING INHERITANCE
print("\n" + "="*70)
print("🔹 EXAMPLE 3: Using Inheritance")
print("="*70)

dog = Dog("Rex", 3, "Labrador")
dog.make_sound()
dog.fetch_ball()

cat = Cat("Mimi", 2)
cat.make_sound()
cat.scratch_sofa()


# ═════════════════════════════════════════════════════════════════════════════
# 📌 EXAMPLE 4: MORE COMPLETE CLASS - PRODUCT 📌
# ═════════════════════════════════════════════════════════════════════════════

class Product:
    """
    Class that represents a Product in a store.
    Demonstrates attributes, methods and useful operations.
    """
    
    def __init__(self, name: str, price: float, quantity: int):
        self.name = name
        self.price = price
        self.quantity = quantity
    
    def calculate_total_value(self) -> float:
        """Calculates the total value of the stock."""
        return self.price * self.quantity
    
    def apply_discount(self, percentage: float) -> None:
        """Applies a percentage discount to the price."""
        discount = self.price * (percentage / 100)
        self.price -= discount
        print(f"🏷️  {percentage}% discount applied! New price: ${self.price:.2f}")
    
    def sell(self, quantity: int) -> bool:
        """Sells a quantity of products."""
        if quantity > self.quantity:
            print(f"❌ Error: Only {self.quantity} units available!")
            return False
        
        self.quantity -= quantity
        print(f"✅ {quantity} unit(s) of '{self.name}' sold!")
        return True
    
    def restock(self, quantity: int) -> None:
        """Restocks the inventory."""
        self.quantity += quantity
        print(f"📦 Stock replenished! Now there are {self.quantity} units.")
    
    def display_information(self) -> None:
        """Displays all product information."""
        print(f"\n📦 PRODUCT: {self.name}")
        print(f"   💵 Price: ${self.price:.2f}")
        print(f"   📊 Quantity: {self.quantity} units")
        print(f"   💰 Total Value: ${self.calculate_total_value():.2f}")


# 🔹 USING THE PRODUCT CLASS
print("\n" + "="*70)
print("🔹 EXAMPLE 4: Using the Product Class")
print("="*70)

product1 = Product("Laptop", 3500.00, 5)
product1.display_information()

product1.sell(2)
product1.apply_discount(10)
product1.display_information()


# ═════════════════════════════════════════════════════════════════════════════
# 📌 SUMMARY OF CONCEPTS 📌
# ═════════════════════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("📚 SUMMARY OF CONCEPTS")
print("="*70)

summary = """
✅ CLASS: A blueprint for creating objects
   • Defines attributes (characteristics)
   • Defines methods (actions/behaviors)

✅ OBJECT/INSTANCE: A real copy of a class
   • Created using the __init__ constructor
   • Has its own values for attributes

✅ ATTRIBUTE: A variable that belongs to the class
   • Store data about the object
   • Accessed using self.attribute

✅ METHOD: A function that belongs to the class
   • Performs actions on the object
   • First parameter is always "self"

✅ CONSTRUCTOR (__init__): Special method
   • Called automatically when creating an object
   • Initializes the attributes

✅ ENCAPSULATION: Protect private data
   • Use __ before the attribute to make it private
   • Example: self.__balance (don't access directly)

✅ INHERITANCE: A class inherits from another
   • PARENT class: contains common characteristics
   • CHILD class: inherits and adds its own characteristics
   • Use super().__init__() to call the PARENT constructor

✅ METHOD OVERRIDING: Redefine a PARENT class method
   • The CHILD class can modify the behavior
   • Example: Dog inherits from Animal but make_sound() is different
"""

print(summary)


# ═════════════════════════════════════════════════════════════════════════════
# 🎯 FINAL CHALLENGE 🎯
# ═════════════════════════════════════════════════════════════════════════════

print("\n" + "="*70)
print("🎯 FINAL CHALLENGE - STUDENT MANAGEMENT SYSTEM 🎯")
print("="*70)

challenge = """
Create a STUDENT MANAGEMENT SYSTEM with the following characteristics:

📋 CLASS: Student
   ├─ Attributes:
   │  ├─ Name (string)
   │  ├─ Registration (string) - PRIVATE
   │  ├─ List of grades (list) - PRIVATE
   │  └─ Email (string)
   │
   └─ Methods:
      ├─ add_grade(grade: float) -> None
      │  └─ Adds a grade to the list (validate: 0-10)
      │
      ├─ calculate_average() -> float
      │  └─ Returns the arithmetic mean of the grades
      │
      ├─ get_status() -> str
      │  └─ Returns "Approved" (average >= 7) or "Failed"
      │
      ├─ list_grades() -> None
      │  └─ Displays all student grades
      │
      └─ display_information() -> None
         └─ Displays: Name, Registration, Grades, Average and Status

🎓 CLASS: Class
   ├─ Attributes:
   │  ├─ Class name (string)
   │  └─ List of students (list) - PRIVATE
   │
   └─ Methods:
      ├─ add_student(student: Student) -> None
      │  └─ Adds a student to the class
      │
      ├─ list_students() -> None
      │  └─ Displays all students in the class
      │
      ├─ calculate_class_average() -> float
      │  └─ Calculates the overall class average
      │
      └─ approved_students() -> int
         └─ Returns how many students passed

💡 BONUS CHALLENGE (Optional):
   • Create a Teacher class that inherits from Student
   • Add attributes: subject (string) and experience (int)
   • Add method: teach_class() that displays a message

📝 USAGE EXAMPLE:
   student1 = Student("John", "2024001", "john@email.com")
   student1.add_grade(8.5)
   student1.add_grade(9.0)
   student1.add_grade(7.5)
   student1.display_information()
   
   class_a = Class("Class A")
   class_a.add_student(student1)
   class_a.list_students()
   class_a.calculate_class_average()

✨ GOOD LUCK! ✨
"""

print(challenge)


# ═════════════════════════════════════════════════════════════════════════════
# 📌 TIPS FOR SOLVING THE CHALLENGE 📌
# ═════════════════════════════════════════════════════════════════════════════

tips = """
💡 TIPS FOR SOLVING THE CHALLENGE:

1️⃣ Start with the Student class
   • Use type hints on all parameters and return values
   • Validate grades (must be between 0 and 10)
   • Use __init__ to initialize the attributes

2️⃣ Implement each method carefully
   • calculate_average(): use sum() and len() of the grades list
   • get_status(): check if average >= 7
   • display_information(): use f-string for formatting

3️⃣ Create the Class class
   • Store students in a private list
   • list_students(): iterate over the list with for
   • calculate_class_average(): sum the averages of all students

4️⃣ Test your code
   • Create some students
   • Add grades
   • Check if calculations are correct

5️⃣ For the bonus (Teacher class)
   • Use inheritance: class Teacher(Student):
   • Use super().__init__() in the constructor
   • Add Teacher's own attributes

┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

✅ When you finish, you will have practiced:
   ✓ Creating classes
   ✓ Attributes and methods
   ✓ Type hints
   ✓ Data validation
   ✓ Lists and iteration
   ✓ Encapsulation
   ✓ Inheritance (bonus)

Good luck! 🚀
"""

print(tips)
